/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ITheTapestry, ITheTapestryInterface } from "../ITheTapestry";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "chapterIndex",
        type: "uint256",
      },
    ],
    name: "isChapterComplete",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "weaver",
        type: "address",
      },
    ],
    name: "linesByWeaver",
    outputs: [
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ITheTapestry__factory {
  static readonly abi = _abi;
  static createInterface(): ITheTapestryInterface {
    return new utils.Interface(_abi) as ITheTapestryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITheTapestry {
    return new Contract(address, _abi, signerOrProvider) as ITheTapestry;
  }
}
